# Generated by Django 3.0.8 on 2020-09-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20200906_0856'),
        ('recruiter', '0003_auto_20200906_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Job')),
            ],
            options={
                'db_table': 'candidate_job',
            },
        ),
    ]
