# Generated by Django 3.0.8 on 2020-09-06 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_candidatejob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejob',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 6, 11, 53, 49, 587087, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
